export const INDUSTRY_CATEGORIES = [
  'Agriculture & Agribusiness',
  'Automotive & Mobility',
  'Banking & Financial Services',
  'Construction & Real Estate',
  'Consumer Goods & Retail',
  'Creative Arts & Entertainment',
  'Education & Training',
  'Energy, Oil & Gas',
  'Engineering & Manufacturing',
  'Environmental Services',
  'Fashion & Beauty',
  'Food, Hospitality & Tourism',
  'Government & Public Sector',
  'Healthcare & Life Sciences',
  'Information Technology & Telecommunications',
  'Insurance',
  'Legal & Regulatory',
  'Logistics, Transport & Supply Chain',
  'Media, Marketing & Communications',
  'Mining & Natural Resources',
  'Non-profit & Social Impact',
  'Professional & Business Services',
  'Recruitment & Human Resources',
  'Security & Safety',
  'Sports & Fitness',
  'Other',
] as const

export const PROFESSIONAL_SERVICE_CATEGORIES = [
  'Accounting & Audit',
  'Architecture',
  'Banking & Investment',
  'Business Analysis',
  'Business Consulting',
  'Civil Engineering',
  'Data Analysis & Business Intelligence',
  'Education & Training',
  'Electrical & Electronics Engineering',
  'Environmental Consulting',
  'Finance & Financial Planning',
  'Graphic & Product Design',
  'Healthcare & Clinical Services',
  'Human Resources',
  'Insurance & Risk Management',
  'Legal Services',
  'Marketing & Brand Strategy',
  'Mechanical Engineering',
  'Media & Communications',
  'Operations Management',
  'Procurement & Supply Chain',
  'Product Management',
  'Project Management',
  'Property & Estate Management',
  'Quality Assurance',
  'Research & Policy',
  'Sales & Business Development',
  'Software Engineering',
  'Tax Consulting',
  'Telecommunications',
  'UI/UX Design',
  'Other Professional Services',
] as const

export const PROFESSIONAL_QUALIFICATIONS = [
  'Diploma / OND',
  'HND',
  "Bachelor's degree",
  'Postgraduate diploma',
  "Master's degree",
  'Doctorate',
  'Professional certification',
  'Other',
] as const

export const COMPANY_SIZES = [
  '1-10 employees',
  '11-50 employees',
  '51-200 employees',
  '201-500 employees',
  '501-1,000 employees',
  '1,001-5,000 employees',
  '5,001+ employees',
] as const

export const RECRUITMENT_FUNCTIONS = [
  'General Recruitment & Staffing',
  'Executive Search',
  'Graduate & Entry-Level Recruitment',
  'Technical & Engineering Recruitment',
  'Technology Recruitment',
  'Healthcare Recruitment',
  'Legal Recruitment',
  'Finance & Accounting Recruitment',
  'Sales & Marketing Recruitment',
  'Operations & Supply Chain Recruitment',
  'Artisan & Skilled Trades Recruitment',
  'Temporary & Contract Staffing',
  'Internal Human Resources',
  'Talent Consulting / Outsourcing',
  'Other',
] as const

export type IndustryCategory = typeof INDUSTRY_CATEGORIES[number]
export type ProfessionalServiceCategory = typeof PROFESSIONAL_SERVICE_CATEGORIES[number]
export type CompanySize = typeof COMPANY_SIZES[number]
export type RecruitmentFunction = typeof RECRUITMENT_FUNCTIONS[number]
