export const INDUSTRY_CATEGORIES = [
  'Agriculture & Agribusiness',
  'Automotive & Mobility',
  'Banking & Financial Services',
  'Construction & Real Estate',
  'Consumer Goods & Retail',
  'Creative Arts & Entertainment',
  'Education & Training',
  'Energy, Oil & Gas',
  'Engineering & Manufacturing',
  'Environmental Services',
  'Fashion & Beauty',
  'Food, Hospitality & Tourism',
  'Government & Public Sector',
  'Healthcare & Life Sciences',
  'Information Technology & Telecommunications',
  'Insurance',
  'Legal & Regulatory',
  'Logistics, Transport & Supply Chain',
  'Media, Marketing & Communications',
  'Mining & Natural Resources',
  'Non-profit & Social Impact',
  'Professional & Business Services',
  'Recruitment & Human Resources',
  'Security & Safety',
  'Sports & Fitness',
  'Other',
] as const

export const PROFESSIONAL_SERVICE_CATEGORIES = [
  'Accounting & Audit',
  'Architecture',
  'Banking & Investment',
  'Business Analysis',
  'Business Consulting',
  'Civil Engineering',
  'Data Analysis & Business Intelligence',
  'Education & Training',
  'Electrical & Electronics Engineering',
  'Environmental Consulting',
  'Finance & Financial Planning',
  'Graphic & Product Design',
  'Healthcare & Clinical Services',
  'Human Resources',
  'Insurance & Risk Management',
  'Legal Services',
  'Marketing & Brand Strategy',
  'Mechanical Engineering',
  'Media & Communications',
  'Operations Management',
  'Procurement & Supply Chain',
  'Product Management',
  'Project Management',
  'Property & Estate Management',
  'Quality Assurance',
  'Research & Policy',
  'Sales & Business Development',
  'Software Engineering',
  'Tax Consulting',
  'Telecommunications',
  'UI/UX Design',
  'Other Professional Services',
] as const

export const PROFESSIONAL_QUALIFICATIONS = [
  'FSLC – First School Leaving Certificate',
  'SSCE – Senior Secondary School Certificate',
  'WAEC',
  'NECO',
  'GCE',
  'NABTEB',
  'NCE – Nigeria Certificate in Education',
  'OND – Ordinary National Diploma',
  'HND – Higher National Diploma',
  'B.Sc. – Bachelor of Science',
  'B.A. – Bachelor of Arts',
  'B.Tech. – Bachelor of Technology',
  'B.Eng. – Bachelor of Engineering',
  'LL.B. – Bachelor of Laws',
  'MBBS – Bachelor of Medicine, Bachelor of Surgery',
  'B.Pharm – Bachelor of Pharmacy',
  'B.Ed. – Bachelor of Education',
  'M.Sc. – Master of Science',
  'M.A. – Master of Arts',
  'M.Tech. – Master of Technology',
  'M.Eng. – Master of Engineering',
  'MBA – Master of Business Administration',
  'MPA – Master of Public Administration',
  'PGD – Postgraduate Diploma',
  'Ph.D. – Doctor of Philosophy',
] as const

export const COMPANY_SIZES = [
  '1-10 employees',
  '11-50 employees',
  '51-200 employees',
  '201-500 employees',
  '501-1,000 employees',
  '1,001-5,000 employees',
  '5,001+ employees',
] as const

export const RECRUITMENT_FUNCTIONS = [
  'General Recruitment & Staffing',
  'Executive Search',
  'Graduate & Entry-Level Recruitment',
  'Technical & Engineering Recruitment',
  'Technology Recruitment',
  'Healthcare Recruitment',
  'Legal Recruitment',
  'Finance & Accounting Recruitment',
  'Sales & Marketing Recruitment',
  'Operations & Supply Chain Recruitment',
  'Artisan & Skilled Trades Recruitment',
  'Temporary & Contract Staffing',
  'Internal Human Resources',
  'Talent Consulting / Outsourcing',
  'Other',
] as const

export type IndustryCategory = typeof INDUSTRY_CATEGORIES[number]
export type ProfessionalServiceCategory = typeof PROFESSIONAL_SERVICE_CATEGORIES[number]
export type CompanySize = typeof COMPANY_SIZES[number]
export type RecruitmentFunction = typeof RECRUITMENT_FUNCTIONS[number]
