SET SESSION sql_mode = 'ALLOW_INVALID_DATES,NO_ENGINE_SUBSTITUTION';

ALTER TABLE businesses
  MODIFY COLUMN dateSubscribed DATE NULL DEFAULT NULL,
  MODIFY COLUMN expiryDate DATE NULL DEFAULT NULL,
  MODIFY COLUMN lga VARCHAR(100) DEFAULT NULL,
  MODIFY COLUMN location VARCHAR(500) DEFAULT '';

UPDATE businesses
SET dateSubscribed = NULL
WHERE dateSubscribed = '0000-00-00';

UPDATE businesses
SET expiryDate = NULL
WHERE expiryDate = '0000-00-00';
